version: 0.2

phases:
  pre_build:
    commands:
      - export CURRENT_DATE=`date '+%Y%m%d%H%M%S'`
      - npm install -g yarn
      - yarn global add newman
      - yarn global add newman-reporter-html
      - yarn install
  build:
    commands:
      - echo Build started on `date`
      - yarn test
  
